"use client";

import { Spinner } from "sid-ui";
import dynamic from "next/dynamic";
import { createElement, type ComponentType } from "react";

const loading = () => createElement(Spinner, { label: "Loading example" });

export const DEMO_COMPONENTS: Record<string, ComponentType> = {
  brand: dynamic(() => import("./brand"), { ssr: false, loading }),
  "brand-heading": dynamic(() => import("./brand-heading"), { ssr: false, loading }),
  "brand-lockup": dynamic(() => import("./brand-lockup"), { ssr: false, loading }),
  "brand-footer": dynamic(() => import("./brand-footer"), { ssr: false, loading }),
  "google-sign-in-button": dynamic(() => import("./google-sign-in-button"), {
    ssr: false,
    loading,
  }),
  button: dynamic(() => import("./button"), { ssr: false, loading }),
  "button-group": dynamic(() => import("./button-group"), { ssr: false, loading }),
  "icon-button": dynamic(() => import("./icon-button"), { ssr: false, loading }),
  link: dynamic(() => import("./link"), { ssr: false, loading }),
  "dropdown-menu": dynamic(() => import("./dropdown-menu"), { ssr: false, loading }),
  "more-menu": dynamic(() => import("./more-menu"), { ssr: false, loading }),
  "segmented-control": dynamic(() => import("./segmented-control"), { ssr: false, loading }),
  "toggle-button": dynamic(() => import("./toggle-button"), { ssr: false, loading }),
  "toggle-button-group": dynamic(() => import("./toggle-button-group"), { ssr: false, loading }),
  toolbar: dynamic(() => import("./toolbar"), { ssr: false, loading }),
  "app-shell": dynamic(() => import("./app-shell"), { ssr: false, loading }),
  "aspect-ratio": dynamic(() => import("./aspect-ratio"), { ssr: false, loading }),
  divider: dynamic(() => import("./divider"), { ssr: false, loading }),
  "form-layout": dynamic(() => import("./form-layout"), { ssr: false, loading }),
  grid: dynamic(() => import("./grid"), { ssr: false, loading }),
  layout: dynamic(() => import("./layout"), { ssr: false, loading }),
  section: dynamic(() => import("./section"), { ssr: false, loading }),
  stack: dynamic(() => import("./stack"), { ssr: false, loading }),
  "resize-handle": dynamic(() => import("./resize-handle"), { ssr: false, loading }),
  "scrollable-area": dynamic(() => import("./scrollable-area"), { ssr: false, loading }),
  sticky: dynamic(() => import("./sticky"), { ssr: false, loading }),
  avatar: dynamic(() => import("./avatar"), { ssr: false, loading }),
  blockquote: dynamic(() => import("./blockquote"), { ssr: false, loading }),
  citation: dynamic(() => import("./citation"), { ssr: false, loading }),
  code: dynamic(() => import("./code"), { ssr: false, loading }),
  "code-block": dynamic(() => import("./code-block"), { ssr: false, loading }),
  "empty-state": dynamic(() => import("./empty-state"), { ssr: false, loading }),
  glyph: dynamic(() => import("./glyph"), { ssr: false, loading }),
  heading: dynamic(() => import("./heading"), { ssr: false, loading }),
  icon: dynamic(() => import("./icon"), { ssr: false, loading }),
  kbd: dynamic(() => import("./kbd"), { ssr: false, loading }),
  markdown: dynamic(() => import("./markdown"), { ssr: false, loading }),
  text: dynamic(() => import("./text"), { ssr: false, loading }),
  thumbnail: dynamic(() => import("./thumbnail"), { ssr: false, loading }),
  timestamp: dynamic(() => import("./timestamp"), { ssr: false, loading }),
  token: dynamic(() => import("./token"), { ssr: false, loading }),
  card: dynamic(() => import("./card"), { ssr: false, loading }),
  carousel: dynamic(() => import("./carousel"), { ssr: false, loading }),
  collapsible: dynamic(() => import("./collapsible"), { ssr: false, loading }),
  "address-selector": dynamic(() => import("./address-selector"), { ssr: false, loading }),
  calendar: dynamic(() => import("./calendar"), { ssr: false, loading }),
  "city-selector": dynamic(() => import("./city-selector"), { ssr: false, loading }),
  checkbox: dynamic(() => import("./checkbox"), { ssr: false, loading }),
  "date-input": dynamic(() => import("./date-input"), { ssr: false, loading }),
  field: dynamic(() => import("./field"), { ssr: false, loading }),
  "file-input": dynamic(() => import("./file-input"), { ssr: false, loading }),
  "number-input": dynamic(() => import("./number-input"), { ssr: false, loading }),
  radio: dynamic(() => import("./radio"), { ssr: false, loading }),
  rating: dynamic(() => import("./rating"), { ssr: false, loading }),
  "code-input": dynamic(() => import("./code-input"), { ssr: false, loading }),
  select: dynamic(() => import("./select"), { ssr: false, loading }),
  slider: dynamic(() => import("./slider"), { ssr: false, loading }),
  switch: dynamic(() => import("./switch"), { ssr: false, loading }),
  "text-area": dynamic(() => import("./text-area"), { ssr: false, loading }),
  "text-input": dynamic(() => import("./text-input"), { ssr: false, loading }),
  "time-input": dynamic(() => import("./time-input"), { ssr: false, loading }),
  tokenizer: dynamic(() => import("./tokenizer"), { ssr: false, loading }),
  typeahead: dynamic(() => import("./typeahead"), { ssr: false, loading }),
  badge: dynamic(() => import("./badge"), { ssr: false, loading }),
  banner: dynamic(() => import("./banner"), { ssr: false, loading }),
  notification: dynamic(() => import("./notification"), { ssr: false, loading }),
  "progress-bar": dynamic(() => import("./progress-bar"), { ssr: false, loading }),
  skeleton: dynamic(() => import("./skeleton"), { ssr: false, loading }),
  spinner: dynamic(() => import("./spinner"), { ssr: false, loading }),
  "state-selector": dynamic(() => import("./state-selector"), { ssr: false, loading }),
  "status-dot": dynamic(() => import("./status-dot"), { ssr: false, loading }),
  toast: dynamic(() => import("./toast"), { ssr: false, loading }),
  breadcrumbs: dynamic(() => import("./breadcrumbs"), { ssr: false, loading }),
  pagination: dynamic(() => import("./pagination"), { ssr: false, loading }),
  "pill-nav": dynamic(() => import("./pill-nav"), { ssr: false, loading }),
  "side-nav": dynamic(() => import("./side-nav"), { ssr: false, loading }),
  stepper: dynamic(() => import("./stepper"), { ssr: false, loading }),
  "tab-list": dynamic(() => import("./tab-list"), { ssr: false, loading }),
  "top-nav": dynamic(() => import("./top-nav"), { ssr: false, loading }),
  "bottom-sheet": dynamic(() => import("./bottom-sheet"), { ssr: false, loading }),
  "command-palette": dynamic(() => import("./command-palette"), { ssr: false, loading }),
  "context-menu": dynamic(() => import("./context-menu"), { ssr: false, loading }),
  dialog: dynamic(() => import("./dialog"), { ssr: false, loading }),
  drawer: dynamic(() => import("./drawer"), { ssr: false, loading }),
  "hover-card": dynamic(() => import("./hover-card"), { ssr: false, loading }),
  popover: dynamic(() => import("./popover"), { ssr: false, loading }),
  tooltip: dynamic(() => import("./tooltip"), { ssr: false, loading }),
  list: dynamic(() => import("./list"), { ssr: false, loading }),
  "metadata-list": dynamic(() => import("./metadata-list"), { ssr: false, loading }),
  "overflow-list": dynamic(() => import("./overflow-list"), { ssr: false, loading }),
  table: dynamic(() => import("./table"), { ssr: false, loading }),
  kanban: dynamic(() => import("./kanban"), { ssr: false, loading }),
  timeline: dynamic(() => import("./timeline"), { ssr: false, loading }),
  "tree-list": dynamic(() => import("./tree-list"), { ssr: false, loading }),
  "message-list": dynamic(() => import("./message-list"), { ssr: false, loading }),
  "trend-chart": dynamic(() => import("./trend-chart"), { ssr: false, loading }),
  "bar-chart": dynamic(() => import("./bar-chart"), { ssr: false, loading }),
  "donut-chart": dynamic(() => import("./donut-chart"), { ssr: false, loading }),
  "funnel-chart": dynamic(() => import("./funnel-chart"), { ssr: false, loading }),
  "heatmap-calendar": dynamic(() => import("./heatmap-calendar"), { ssr: false, loading }),
  sparkline: dynamic(() => import("./sparkline"), { ssr: false, loading }),
  chat: dynamic(() => import("./chat"), { ssr: false, loading }),
  "visually-hidden": dynamic(() => import("./visually-hidden"), { ssr: false, loading }),
};
