/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/joined.theme.ts
 * Command: astryx theme build src/theme/joined.theme.ts --out src/theme/theme.css
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.6.2
 */

/// <reference path="./joined.variants.d.ts" />
import type { DefinedTheme } from "@astryxdesign/core/theme";
export declare const joinedTheme: DefinedTheme;
